name: clean_framework_firestore
description: A wrapper around cloud_firestore to make it easier to use with clean_framework.
version: 0.2.0-dev.0
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework/packages/clean_framework_firestore

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^2.0.0-dev.0
  cloud_firestore: ^4.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  clean_framework_test: ^0.2.0-dev.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
