name: clean_framework_example
description: Sandbox with example of all components from clean framework
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework:
    path: ../

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
  equatable: ^2.0.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flags.json
