name: clean_framework_router
description: A wrapper around go_router to make it easier to use with clean_framework.
version: 0.5.14
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/tree/main/packages/clean_framework_router

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

resolution: workspace

dependencies:
  clean_framework: ^4.1.4

  flutter:
    sdk: flutter
  go_router: ^18.0.0
  material_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
