name: clean_framework_router
description: A wrapper around go_router to make it easier to use with clean_framework.
version: 0.5.0
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/packages/clean_framework_router

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^3.0.0
  flutter:
    sdk: flutter
  go_router: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
