name: clean_framework_router
description: A wrapper around go_router to make it easier to use with clean_framework.
version: 0.5.10-dev.1
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/tree/main/packages/clean_framework_router

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^4.0.0-dev.0

  flutter:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
