name: clean_framework_router
description: A wrapper around go_router to make it easier to use with clean_framework.
version: 0.4.3
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/packages/clean_framework_router

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^2.1.3
  flutter:
    sdk: flutter
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
