name: clean_framework_router
description: A wrapper around go_router to make it easier to use with clean_framework.
version: 0.5.10-dev.0
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/tree/main/packages/clean_framework_router
# TODO(Chris): Remove when publishing.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  # clean_framework: '>= 3.2.5 <=4.0.0-dev.0'
  clean_framework:
    git: 
      url: https://github.com/ChrisCostanzo-acme/clean_framework.git
      path: packages/clean_framework
      ref: chris/domain-refactors

  flutter:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
