name: clean_framework_test
description: A collection test helpers to support clean_framework.
version: 0.4.4
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/packages/clean_framework_test

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^2.0.9
  clean_framework_router: ^0.4.1
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_test:
    sdk: flutter
  meta: '>=1.8.0 <2.0.0'
  mocktail: ^0.3.0

dev_dependencies:
  very_good_analysis: ^4.0.0+1
