name: clean_framework_test
description: A collection test helpers to support clean_framework.
version: 0.2.0
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework/packages/clean_framework_test

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^2.0.0
  clean_framework_router: ^0.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_test:
    sdk: flutter
  meta: '>=1.8.0 <1.9.0'

dev_dependencies:
  very_good_analysis: ^3.1.0
