name: clean_framework_test
description: A collection test helpers to support clean_framework.
version: 0.5.3
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/packages/clean_framework_test

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^4.0.0
  clean_framework_router: ^0.5.10

  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_test:
    sdk: flutter
  meta: '>=1.8.0 <2.0.0'
  mocktail: ^1.0.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
