name: clean_framework_http
description: External Interface for clean_framework package based on Dio.
version: 0.1.2
homepage: https://acmesoftware.com

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  clean_framework: ^2.1.0
  dio: ^5.0.2

dev_dependencies:
  clean_framework_test: ^0.4.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1