name: clean_framework_core
description: A package containting core classes necessary for clean_framework.
version: 0.1.0
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework/packages/clean_framework_core

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  go_router: ^4.5.1
