name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 4.1.4
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework
screenshots:
  - description: 'Clean Framework'
    path: screenshots/clean-framework.png
topics:
  - clean-architecture
  - clean
  - framework
  - feature-flag

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

resolution: workspace

dependencies:
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  material_ui: ^1.1.0
  meta: '>=1.12.0 <2.0.0'
  stack_trace: '>=1.11.0 <2.0.0'
  uniform: ^2.0.7

dev_dependencies:
  clean_framework_test: ^0.5.5

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0
