name: example
description: Sandbox with example of all components from clean framework
version: 1.5.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework: ^2.0.4
  clean_framework_firestore: ^0.4.0
  clean_framework_graphql: ^0.4.0
  clean_framework_rest: ^0.4.0
  clean_framework_router: ^0.4.0
  intl: ^0.18.0

dev_dependencies:
  clean_framework_test: ^0.4.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  equatable: ^2.0.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flags.json
