name: clean_framework_rest
description: A wrapper around http to make it easier to use with clean_framework.
version: 0.4.1
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework/packages/clean_framework_rest

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework: ^2.0.9
  cross_file: ^0.3.3+4
  flutter:
    sdk: flutter
  http: ^0.13.5
  meta: '>=1.8.0 <2.0.0'
  path: '>=1.8.2 <1.9.0'

dev_dependencies:
  clean_framework_test: ^0.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
