name: clean_framework_rest
description: A wrapper around http to make it easier to use with clean_framework.
version: 0.1.0
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework/packages/clean_framework_rest

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  clean_framework:
    path:
      ../clean_framework
  flutter:
    sdk: flutter
  http: ^0.13.5
  cross_file: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
