name: Deploy to Web

on:
  push:
    branches:
      - main
      - develop

jobs:
  web-deploy:
    name: Web Deploy
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: sarbagyastha/flutter-gh-pages@main
        with:
          workingDir: packages/clean_framework/example
